// Generated by CoffeeScript 1.9.1
var Game;

Game = {
  _display: null,
  _currentScreen: null,
  init: function() {
    var bindEventToScreen, game;
    this._display = new ROT.Display({
      width: 80,
      height: 24
    });
    game = this;
    bindEventToScreen = function(event) {
      return window.addEventListener(event, function(e) {
        if (game._currentScreen !== null) {
          return game._currentScreen.handleInput(event, e);
        }
      });
    };
    bindEventToScreen("keydown");
    bindEventToScreen("keyup");
    return bindEventToScreen("keypress");
  },
  getDisplay: function() {
    return this._display;
  },
  switchScreen: function(screen) {
    if (this._currentScreen !== null) {
      this._currentScreen.exit();
    }
    this.getDisplay().clear();
    this._currentScreen = screen;
    if (this._currentScreen !== null) {
      this._currentScreen.enter();
      return this._currentScreen.render(this._display);
    }
  }
};

window.onload = function(event) {
  if (!ROT.isSupported()) {
    return alert("Rot is not Supported");
  } else {
    Game.init();
    document.body.appendChild(Game.getDisplay().getContainer());
    return Game.switchScreen(Game.Screen.startScreen);
  }
};
