// Generated by CoffeeScript 1.9.1
var Glyph;

Glyph = (function() {
  function Glyph(symbol, foreground, background) {
    this._char = symbol || ' ';
    this._foreground = foreground || 'white';
    this._background - background || 'black';
  }

  Glyph.prototype.getChar = function() {
    return this._char;
  };

  Glyph.prototype.getForeground = function() {
    return this._foreground;
  };

  Glyph.prototype.getBackground = function() {
    return this._background;
  };

  return Glyph;

})();

Game.Glyph = Glyph;
