// Generated by CoffeeScript 1.9.1
var Map;

Map = (function() {
  function Map(tiles) {
    this._tiles = tiles;
    this._width = tiles.length;
    this._height = tiles[0].length;
  }

  Map.prototype.getWidth = function() {
    return this._width;
  };

  Map.prototype.getHeight = function() {
    return this._height;
  };

  Map.prototype.getTile = function(x, y) {
    if (x >= 0 && x < this._width && y >= 0 && y < this._height) {
      return this._tiles[x][y] || Game.Tile.nullTile;
    } else {
      return Game.Tile.nullTile;
    }
  };

  return Map;

})();

Game.Map = Map;
