// Generated by CoffeeScript 1.9.1
var Tile;

Tile = (function() {
  function Tile(glyph) {
    this._glyph = glyph;
  }

  Tile.prototype.getGlyph = function() {
    return this._glyph;
  };

  return Tile;

})();

Game.Tile = Tile;

Game.Tile.nullTile = new Game.Tile(new Game.Glyph());

Game.Tile.wallTile = new Game.Tile(new Game.Glyph('#', 'goldenrod'));

Game.Tile.floorTile = new Game.Tile(new Game.Glyph('.'));
